# Generated by Django 3.0 on 2021-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210407_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='True', default='', null='True', upload_to='user_image/'),
            preserve_default='True',
        ),
    ]
