# Generated by Django 3.0 on 2021-04-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category', models.CharField(max_length=100)),
                ('Product_company', models.CharField(max_length=100)),
                ('Product_price', models.CharField(max_length=100)),
                ('Product_color', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(upload_to='ProductImage/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
