# Generated by Django 3.0 on 2021-04-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_color',
            new_name='product_color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_company',
            new_name='product_company',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_price',
            new_name='product_price',
        ),
    ]
