# Generated by Django 3.0 on 2021-04-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_company',
            new_name='product_model',
        ),
    ]
