# Generated by Django 3.0 on 2021-04-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210419_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dec',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
