# Generated by Django 3.0 on 2021-04-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paymate_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.User'),
        ),
    ]
