# Generated by Django 3.0 on 2021-04-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210429_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='paymate_status',
            new_name='payment_status',
        ),
    ]
