# Generated by Django 3.0 on 2021-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210430_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cart',
            field=models.CharField(default='', max_length=100),
        ),
    ]
