# Generated by Django 3.0 on 2021-04-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_transaction_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='carts',
            field=models.ForeignKey(blank='True', default='', null='True', on_delete=django.db.models.deletion.CASCADE, to='myapp.Cart'),
            preserve_default='True',
        ),
    ]
