# Generated by Django 3.0 on 2021-04-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210430_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='carts',
            new_name='cart',
        ),
    ]
